
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CAST = 45;
  public static final int MASMAS = 41;
  public static final int MENOSMENOS = 42;
  public static final int AC = 8;
  public static final int MULT = 28;
  public static final int CHAR = 21;
  public static final int OLOG = 38;
  public static final int ENTERO = 22;
  public static final int DIFERENTE = 36;
  public static final int YLOG = 37;
  public static final int INT = 19;
  public static final int FOR = 14;
  public static final int C_LLAVE = 3;
  public static final int A_LLAVE = 2;
  public static final int CP = 6;
  public static final int IGUAL = 35;
  public static final int CARACTER = 23;
  public static final int ASIGNA = 30;
  public static final int CC = 9;
  public static final int IF = 10;
  public static final int EOF = 0;
  public static final int ADMIR = 39;
  public static final int error = 1;
  public static final int COMA = 7;
  public static final int MENOS = 27;
  public static final int MENOR = 31;
  public static final int IDENT = 25;
  public static final int MENOSUNARIO = 40;
  public static final int PCOMA = 4;
  public static final int REAL = 24;
  public static final int MAYOR = 33;
  public static final int PORCENT = 43;
  public static final int ELSE = 11;
  public static final int MAYORIG = 34;
  public static final int TO = 16;
  public static final int WHILE = 12;
  public static final int FLOAT = 20;
  public static final int MENORIG = 32;
  public static final int DIVID = 29;
  public static final int VIRGU = 44;
  public static final int DOWNTO = 17;
  public static final int AP = 5;
  public static final int PRINT = 15;
  public static final int DO = 13;
  public static final int STEP = 18;
  public static final int MAS = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "A_LLAVE",
  "C_LLAVE",
  "PCOMA",
  "AP",
  "CP",
  "COMA",
  "AC",
  "CC",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PRINT",
  "TO",
  "DOWNTO",
  "STEP",
  "INT",
  "FLOAT",
  "CHAR",
  "ENTERO",
  "CARACTER",
  "REAL",
  "IDENT",
  "MAS",
  "MENOS",
  "MULT",
  "DIVID",
  "ASIGNA",
  "MENOR",
  "MENORIG",
  "MAYOR",
  "MAYORIG",
  "IGUAL",
  "DIFERENTE",
  "YLOG",
  "OLOG",
  "ADMIR",
  "MENOSUNARIO",
  "MASMAS",
  "MENOSMENOS",
  "PORCENT",
  "VIRGU",
  "CAST"
  };
}

